# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "footnotes", "autolink", "tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            node.js 한국 커뮤니티
tagline:          'node.js 한글화'
description:      '<a href="https://nodejs.org" target="_blank">node.js</a> 관련 소식, 정보, 글 등을 한국어로 번역해서 공유합니다.'
url:              http://nodejs.github.io/iojs-ko
baseurl:          /iojs-ko

author:
  name:           'node.js 한국어 번역팀'
  url:            https://github.com/nodejs/iojs-ko

paginate:         5

github:
  repo:           https://github.com/nodejs/iojs-ko
