name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: install
      - name: Generate
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: run generate
