name: Deploy on master
on:
  push:
    branches:
      - master
jobs:
  buildAndDeploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: install
      - name: Generate
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: run generate
      - name: Add rsa key
        uses: actions/bin/sh@24a566c2524e05ebedadef0a285f72dc9b631411
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        with:
          entrypoint: ./bin/generate_rsa
      - name: Publish
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: run publish
